sudo: required
services:
    - docker

before_install:
    - docker build -t proshantomitra/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true proshantomitra/react-test npm test

after_success:
    - docker build -t proshantomitra/multi-client ./client
    - docker build -t proshantomitra/multi-nginx ./nginx 
    - docker build -t proshantomitra/multi-server ./server
    - docker build -t proshantomitra/multi-worker ./worker  
# Login to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to Docker Hub
    - docker push proshantomitra/multi-client
    - docker push proshantomitra/multi-nginx
    - docker push proshantomitra/multi-server
    - docker push proshantomitra/multi-worker
